name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python src/train.py

      - name: Build docker image
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$repo_lower:${{ github.ref_name }} .

      - name: Smoke test
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker run -d -p 8000:8000 --name triage ghcr.io/$repo_lower:${{ github.ref_name }}
          sleep 5
          curl -f http://localhost:8000/health
          curl -f -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"age":0.02, "sex":-0.044, "bmi":0.06, "bp":-0.03, "s1":-0.02, "s2":0.03, "s3":-0.02, "s4":0.02, "s5":0.02, "s6":-0.001}'

      - name: Login to GHCR
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$repo_lower:${{ github.ref_name }}

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Metrics
            ```
            $(cat model/metrics.json)
            ```
            ## Changelog
            $(cat CHANGELOG.md)